managePackageManagerVersions: true
saveExact: true
registries:
  '@aiharanaoya': https://npm.pkg.github.com/
packages:
  - 'apps/*'
catalog:
  typescript: "6.0.3"
allowedDeprecatedVersions:
  glob: "*"
allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@aiharanaoya/ui@0.2.0'
